### ISSUE TITLE
error

### ISSUE THREAD

**Issue by punkhooren** [NCCA/QtNGL#2]
[ 14%] Automatic moc and uic for target QtNGL
Generating ui_MainWindow.h
File '/home/ren/Compile/NGL/QtNGL-master/src/MainWindow.ui' is not valid
AUTOUIC: error: process for ui_MainWindow.h needed by
 "/home/ren/Compile/NGL/QtNGL-master/src/MainWindow.cpp"
failed:
File '/home/ren/Compile/NGL/QtNGL-master/src/MainWindow.ui' is not valid

Generating moc_MainWindow.cpp
Generating moc_NGLScene.cpp
uic failed...
make[2]: **\* [CMakeFiles/QtNGL_automoc] Error 1
make[1]: **\* [CMakeFiles/QtNGL_automoc.dir/all] Error 2
make: **\* [all] Error 2

**Comment by jmacey** [comment]
There is an error with the Cmake for this project just use qmake as this will work (the problem is the directory structure for cmake is different from the Qt project and I can’t figure out how to fix it at present

On 5 Apr 2016, at 08:40, KeeganRen <notifications@github.com<mailto:notifications@github.com>> wrote:

[ 14%] Automatic moc and uic for target QtNGL
Generating ui_MainWindow.h
File '/home/ren/Compile/NGL/QtNGL-master/src/MainWindow.ui' is not valid
AUTOUIC: error: process for ui_MainWindow.h needed by
"/home/ren/Compile/NGL/QtNGL-master/src/MainWindow.cpp"
failed:
File '/home/ren/Compile/NGL/QtNGL-master/src/MainWindow.ui' is not valid

Generating moc_MainWindow.cpp
Generating moc_NGLScene.cpp
uic failed...
make[2]: **\* [CMakeFiles/QtNGL_automoc] Error 1
make[1]: **\* [CMakeFiles/QtNGL_automoc.dir/all] Error 2
make: **\* [all] Error 2

**Comment by jmacey** [comment]
think I may have fixed it by removing the set(CMAKE_AUTOUIC ON) call, do a pull and see if it fixes it

On 5 Apr 2016, at 08:40, KeeganRen <notifications@github.com<mailto:notifications@github.com>> wrote:

[ 14%] Automatic moc and uic for target QtNGL
Generating ui_MainWindow.h
File '/home/ren/Compile/NGL/QtNGL-master/src/MainWindow.ui' is not valid
AUTOUIC: error: process for ui_MainWindow.h needed by
"/home/ren/Compile/NGL/QtNGL-master/src/MainWindow.cpp"
failed:
File '/home/ren/Compile/NGL/QtNGL-master/src/MainWindow.ui' is not valid

Generating moc_MainWindow.cpp
Generating moc_NGLScene.cpp
uic failed...
make[2]: **\* [CMakeFiles/QtNGL_automoc] Error 1
make[1]: **\* [CMakeFiles/QtNGL_automoc.dir/all] Error 2
make: **\* [all] Error 2

**Comment by punkhooren** [comment]
thanks!
